[package]
name = "dl-server"
version = "0.1.0"
authors = ["sysnet"]
edition = "2018"

[dependencies]
rand = "0.3"
websocket = "0.23.0"

#TODO: This could be removed
futures = { version = "0.1" }
tokio = { version = "0.1" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
